# Yarn will auto-format this file and remove the comments on any automatic updates.
# Please bring the comments back!

compressionLevel: 0

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

globalFolder: .yarn/global

nodeLinker: pnpm

npmMinimalAgeGate: 7d

# This is not enabled by default (requires npmrcAuthEnabled: true or
# YARN_NPMRC_AUTH_ENABLED: 1 which is set in publish.yml)
plugins:
  - checksum: 2e5f3cee593ae105ea74e0a8094ec9277ff39d4c56d185134eb9e05ffd076933053e972545ec0c00a562f04bfb4ef09a414b9d8f177739b8cfe21749d1b035f2
    path: .yarn/plugins/@yarnpkg/plugin-npmrc.cjs
    spec: "https://raw.githubusercontent.com/microsoft/beachball/yarn-plugin-npmrc_v0.5.0/yarn-plugins/npmrc/dist/plugin.dev.js"

npmrcAuthEnabled: true

yarnPath: .yarn/releases/yarn-4.17.0.cjs

